server:
  port: 8090

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

mybatis:
  mapper-locations: classpath:/mybatis/*.xml